In [7]:
import pandas as pd

In [9]:
df = pd.read_csv("E:/GitHub/UFU_MAPPERS/microdados/dados/microdados_ed_basica_2022.csv", delimiter=';', encoding='iso-8859-1', low_memory=False)

In [11]:
df.head(10)

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_MESORREGIAO,CO_MESORREGIAO,...,QT_TUR_FUND_AF,QT_TUR_MED,QT_TUR_PROF,QT_TUR_PROF_TEC,QT_TUR_EJA,QT_TUR_EJA_FUND,QT_TUR_EJA_MED,QT_TUR_ESP,QT_TUR_ESP_CC,QT_TUR_ESP_CE
0,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,0.0,0.0,0.0,0.0,10.0,6.0,4.0,3.0,3.0,0.0
2,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0
5,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,12.0,29.0,0.0,0.0,0.0,0.0,0.0,18.0,18.0,0.0
6,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
7,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
8,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,4.0,8.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0
9,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df_mun = df.loc[df['NO_MUNICIPIO'] == 'Uberlândia']

In [13]:
df_mun.head()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_MESORREGIAO,CO_MESORREGIAO,...,QT_TUR_FUND_AF,QT_TUR_MED,QT_TUR_PROF,QT_TUR_PROF_TEC,QT_TUR_EJA,QT_TUR_EJA_FUND,QT_TUR_EJA_MED,QT_TUR_ESP,QT_TUR_ESP_CC,QT_TUR_ESP_CE
130121,2022,Sudeste,3,Minas Gerais,MG,31,Uberlândia,3170206,Triângulo Mineiro/Alto Paranaíba,5,...,0.0,11.0,14.0,14.0,0.0,0.0,0.0,10.0,10.0,0.0
130122,2022,Sudeste,3,Minas Gerais,MG,31,Uberlândia,3170206,Triângulo Mineiro/Alto Paranaíba,5,...,12.0,0.0,2.0,0.0,4.0,4.0,0.0,32.0,32.0,0.0
130123,2022,Sudeste,3,Minas Gerais,MG,31,Uberlândia,3170206,Triângulo Mineiro/Alto Paranaíba,5,...,0.0,17.0,21.0,21.0,0.0,0.0,0.0,9.0,9.0,0.0
130124,2022,Sudeste,3,Minas Gerais,MG,31,Uberlândia,3170206,Triângulo Mineiro/Alto Paranaíba,5,...,0.0,0.0,15.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
130125,2022,Sudeste,3,Minas Gerais,MG,31,Uberlândia,3170206,Triângulo Mineiro/Alto Paranaíba,5,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,13.0,0.0

In [14]:
df_mun.to_csv('E:/GitHub/UFU_MAPPERS/microdados/dados/microdados_uberlandia_2022.csv', sep=';', encoding='iso-8859-1', index=False)

In [15]:
df_mun['TP_DEPENDENCIA'].value_counts()

4    229
3    142
2     72
1      4
Name: TP_DEPENDENCIA, dtype: int64